-- INSERTS DE JUGADORES (Inicialmente sin clan para que no falle por FK)
INSERT INTO jugadores (id_jugador, nombre_jugador, nivel, experiencia, clan_id) VALUES (1, 'Arthorius', 10, 2500, NULL);
INSERT INTO jugadores (id_jugador, nombre_jugador, nivel, experiencia, clan_id) VALUES (2, 'Elora', 12, 3000, NULL);
INSERT INTO jugadores (id_jugador, nombre_jugador, nivel, experiencia, clan_id) VALUES (3, 'Thorgar', 8, 1900, NULL);
INSERT INTO jugadores (id_jugador, nombre_jugador, nivel, experiencia, clan_id) VALUES (4, 'Lunaris', 14, 3400, NULL);
INSERT INTO jugadores (id_jugador, nombre_jugador, nivel, experiencia, clan_id) VALUES (5, 'Draxor', 9, 2200, NULL);
INSERT INTO jugadores (id_jugador, nombre_jugador, nivel, experiencia, clan_id) VALUES (6, 'Miryel', 7, 1800, NULL);
INSERT INTO jugadores (id_jugador, nombre_jugador, nivel, experiencia, clan_id) VALUES (7, 'Falcon', 15, 3600, NULL);
INSERT INTO jugadores (id_jugador, nombre_jugador, nivel, experiencia, clan_id) VALUES (8, 'Kelron', 13, 3200, NULL);
INSERT INTO jugadores (id_jugador, nombre_jugador, nivel, experiencia, clan_id) VALUES (9, 'Valyria', 10, 2500, NULL);
INSERT INTO jugadores (id_jugador, nombre_jugador, nivel, experiencia, clan_id) VALUES (10, 'Draven', 6, 1600, NULL);
INSERT INTO jugadores (id_jugador, nombre_jugador, nivel, experiencia, clan_id) VALUES (11, 'Leandra', 11, 2800, NULL);
INSERT INTO jugadores (id_jugador, nombre_jugador, nivel, experiencia, clan_id) VALUES (12, 'Zoltan', 12, 3000, NULL);
INSERT INTO jugadores (id_jugador, nombre_jugador, nivel, experiencia, clan_id) VALUES (13, 'Nyrith', 9, 2200, NULL);
INSERT INTO jugadores (id_jugador, nombre_jugador, nivel, experiencia, clan_id) VALUES (14, 'Korvin', 8, 2000, NULL);
INSERT INTO jugadores (id_jugador, nombre_jugador, nivel, experiencia, clan_id) VALUES (15, 'Althea', 10, 2600, NULL);
INSERT INTO jugadores (id_jugador, nombre_jugador, nivel, experiencia, clan_id) VALUES (16, 'Ragnar', 11, 2900, NULL);
INSERT INTO jugadores (id_jugador, nombre_jugador, nivel, experiencia, clan_id) VALUES (17, 'Tyrion', 7, 1700, NULL);
INSERT INTO jugadores (id_jugador, nombre_jugador, nivel, experiencia, clan_id) VALUES (18, 'Sylvan', 6, 1500, NULL);
INSERT INTO jugadores (id_jugador, nombre_jugador, nivel, experiencia, clan_id) VALUES (19, 'Maelis', 9, 2300, NULL);
INSERT INTO jugadores (id_jugador, nombre_jugador, nivel, experiencia, clan_id) VALUES (20, 'Fenris', 12, 3000, NULL);
INSERT INTO jugadores (id_jugador, nombre_jugador, nivel, experiencia, clan_id) VALUES (21, 'Orion', 14, 3400, NULL);
INSERT INTO jugadores (id_jugador, nombre_jugador, nivel, experiencia, clan_id) VALUES (22, 'Yliria', 8, 1900, NULL);
INSERT INTO jugadores (id_jugador, nombre_jugador, nivel, experiencia, clan_id) VALUES (23, 'Bran', 11, 2900, NULL);
INSERT INTO jugadores (id_jugador, nombre_jugador, nivel, experiencia, clan_id) VALUES (24, 'Seraphine', 13, 3200, NULL);
INSERT INTO jugadores (id_jugador, nombre_jugador, nivel, experiencia, clan_id) VALUES (25, 'Eldrin', 15, 3700, NULL);
INSERT INTO jugadores (id_jugador, nombre_jugador, nivel, experiencia, clan_id) VALUES (26, 'Haldor', 7, 1800, NULL);
INSERT INTO jugadores (id_jugador, nombre_jugador, nivel, experiencia, clan_id) VALUES (27, 'Talia', 10, 2600, NULL);
INSERT INTO jugadores (id_jugador, nombre_jugador, nivel, experiencia, clan_id) VALUES (28, 'Drystan', 9, 2200, NULL);
INSERT INTO jugadores (id_jugador, nombre_jugador, nivel, experiencia, clan_id) VALUES (29, 'Kyra', 8, 1900, NULL);
INSERT INTO jugadores (id_jugador, nombre_jugador, nivel, experiencia, clan_id) VALUES (30, 'Varyn', 12, 3000, NULL);

-- INSERTS DE CLANES (Con TO_DATE para la fecha)
INSERT INTO clanes (id_clan, nombre_clan, fecha_creacion, lider_id) VALUES (1, 'Los Dragones Negros', TO_DATE('2021-03-15', 'YYYY-MM-DD'), 1);
INSERT INTO clanes (id_clan, nombre_clan, fecha_creacion, lider_id) VALUES (2, 'Guardianes de Elune', TO_DATE('2020-05-10', 'YYYY-MM-DD'), 2);
INSERT INTO clanes (id_clan, nombre_clan, fecha_creacion, lider_id) VALUES (3, 'Sombras Eternas', TO_DATE('2022-01-25', 'YYYY-MM-DD'), 4);
INSERT INTO clanes (id_clan, nombre_clan, fecha_creacion, lider_id) VALUES (4, 'Espadas de la Luz', TO_DATE('2019-11-30', 'YYYY-MM-DD'), 5);
INSERT INTO clanes (id_clan, nombre_clan, fecha_creacion, lider_id) VALUES (5, 'Furia de los Vientos', TO_DATE('2023-07-07', 'YYYY-MM-DD'), 7);
INSERT INTO clanes (id_clan, nombre_clan, fecha_creacion, lider_id) VALUES (6, 'Legión de Valhalla', TO_DATE('2021-10-19', 'YYYY-MM-DD'), 9);

-- AHORA SÍ ASIGNAMOS LOS CLANES A LOS JUGADORES
UPDATE jugadores SET clan_id = 1 WHERE id_jugador IN (1, 3, 12, 18, 25, 30);
UPDATE jugadores SET clan_id = 2 WHERE id_jugador IN (2, 6, 11, 19, 24);
UPDATE jugadores SET clan_id = 3 WHERE id_jugador IN (4, 8, 14, 20, 26);
UPDATE jugadores SET clan_id = 4 WHERE id_jugador IN (5, 10, 15, 21, 27);
UPDATE jugadores SET clan_id = 5 WHERE id_jugador IN (7, 13, 17, 23, 28);
UPDATE jugadores SET clan_id = 6 WHERE id_jugador IN (9, 16, 22, 29);

-- RECOMPENSAS
INSERT INTO recompensas VALUES (1, 'Oro', '100 piezas de oro.');
INSERT INTO recompensas VALUES (2, 'Espada de Acero', 'Espada larga de acero, aumenta el ataque en 5 puntos.');
INSERT INTO recompensas VALUES (3, 'Poción de Curación', 'Poción que restaura 50 puntos de vida.');
INSERT INTO recompensas VALUES (4, 'Escudo de Madera', 'Escudo de madera resistente, aumenta la defensa en 3 puntos.');
INSERT INTO recompensas VALUES (5, 'Anillo Protector', 'Anillo que otorga +2 a la defensa.');
INSERT INTO recompensas VALUES (6, 'Oro Brillante', '200 piezas de oro brillante, muy valoradas.');
INSERT INTO recompensas VALUES (7, 'Armadura de Cuero', 'Armadura que aumenta la defensa en 4 puntos.');
INSERT INTO recompensas VALUES (8, 'Poción de Mana', 'Poción que restaura 30 puntos de mana.');
INSERT INTO recompensas VALUES (9, 'Hacha de Guerra', 'Hacha que aumenta el ataque en 7 puntos.');
INSERT INTO recompensas VALUES (10, 'Oro Antiguo', '150 piezas de oro antiguo, apreciadas por coleccionistas.');
INSERT INTO recompensas VALUES (11, 'Capa de Invisibilidad', 'Capa que otorga +5 a la evasión.');
INSERT INTO recompensas VALUES (12, 'Báculo Mágico', 'Báculo que aumenta el poder mágico en 6 puntos.');
INSERT INTO recompensas VALUES (13, 'Oro Sagrado', '250 piezas de oro sagrado, usado en rituales.');
INSERT INTO recompensas VALUES (14, 'Guantes de Fuerza', 'Guantes que otorgan +3 al ataque.');
INSERT INTO recompensas VALUES (15, 'Poción de Resistencia', 'Poción que aumenta la salud máxima en 20 puntos temporalmente.');
INSERT INTO recompensas VALUES (16, 'Oro de los Reyes', '300 piezas de oro de los reyes, muy raras.');
INSERT INTO recompensas VALUES (17, 'Espada Encantada', 'Espada con +10 de ataque y probabilidad de daño extra.');
INSERT INTO recompensas VALUES (18, 'Escudo Mágico', 'Escudo que otorga un bono de defensa adicional contra magia.');
INSERT INTO recompensas VALUES (19, 'Oro de la Fortuna', '500 piezas de oro de la fortuna, trae buena suerte.');
INSERT INTO recompensas VALUES (20, 'Tomo de Hechizos', 'Tomo que permite aprender un nuevo hechizo.');
INSERT INTO recompensas VALUES (21, 'Poción de Velocidad', 'Poción que aumenta la agilidad temporalmente.');
INSERT INTO recompensas VALUES (22, 'Cofre de Tesoros', 'Cofre que contiene varios objetos valiosos.');
INSERT INTO recompensas VALUES (23, 'Anillo de Magia', 'Anillo que otorga +5 a la inteligencia.');
INSERT INTO recompensas VALUES (24, 'Oro Valioso', '400 piezas de oro valioso, utilizado en comercio.');
INSERT INTO recompensas VALUES (25, 'Armadura de Acero', 'Armadura que aumenta la defensa en 8 puntos.');
INSERT INTO recompensas VALUES (26, 'Poción de Invulnerabilidad', 'Poción que otorga invulnerabilidad durante 30 segundos.');
INSERT INTO recompensas VALUES (27, 'Oro Legendario', '600 piezas de oro legendario, considerado sagrado.');
INSERT INTO recompensas VALUES (28, 'Espada de Dragón', 'Espada forjada con el metal de un dragón, otorga +15 de ataque.');
INSERT INTO recompensas VALUES (29, 'Cruz de Protección', 'Cruz sagrada que otorga +10 a la defensa contra no-muertos.');
INSERT INTO recompensas VALUES (30, 'Máscara del Mago', 'Máscara que aumenta el poder mágico en 8 puntos.');

-- MONSTRUOS
INSERT INTO monstruos VALUES (1, 'Dragón Rojo', 20, 5000, 'Dragón', 2);
INSERT INTO monstruos VALUES (2, 'Goblin Berserker', 5, 800, 'Goblin', 5);
INSERT INTO monstruos VALUES (3, 'Troll de las Cavernas', 12, 2500, 'Troll', 7);
INSERT INTO monstruos VALUES (4, 'Esqueleto Guerrero', 7, 1000, 'No-Muerto', 4);
INSERT INTO monstruos VALUES (5, 'Demonio del Abismo', 18, 4000, 'Demonio', 6);
INSERT INTO monstruos VALUES (6, 'Lobo Salvaje', 3, 600, 'Bestia', 8);
INSERT INTO monstruos VALUES (7, 'Elemental de Fuego', 15, 3200, 'Elemental', 9);
INSERT INTO monstruos VALUES (8, 'Hidra de Tres Cabezas', 19, 4800, 'Bestia Mítica', 22);
INSERT INTO monstruos VALUES (9, 'Orco Chamán', 10, 2000, 'Orco', 3);
INSERT INTO monstruos VALUES (10, 'Fénix', 22, 5500, 'Ave Mítica', 11);
INSERT INTO monstruos VALUES (11, 'Araña Gigante', 6, 900, 'Bestia', 12);
INSERT INTO monstruos VALUES (12, 'Serpiente Venenosa', 4, 700, 'Reptil', 16);
INSERT INTO monstruos VALUES (13, 'No-Muerto Mayor', 8, 1500, 'No-Muerto', 13);
INSERT INTO monstruos VALUES (14, 'Gigante de la Montaña', 17, 4200, 'Gigante', 14);
INSERT INTO monstruos VALUES (15, 'Bandido Forajido', 5, 800, 'Humano', 1);
INSERT INTO monstruos VALUES (16, 'Hombre Lobo', 11, 2200, 'Licántropo', 15);
INSERT INTO monstruos VALUES (17, 'Minotauro', 14, 3000, 'Bestia Mítica', 17);
INSERT INTO monstruos VALUES (18, 'Hechicero Oscuro', 20, 5000, 'Humano', 18);
INSERT INTO monstruos VALUES (19, 'Ogro Salvaje', 9, 1800, 'Ogro', 26);
INSERT INTO monstruos VALUES (20, 'Serpiente Marina', 16, 3800, 'Reptil', 20);
INSERT INTO monstruos VALUES (21, 'Dragón de Hielo', 21, 5200, 'Dragón', 10);
INSERT INTO monstruos VALUES (22, 'Tigre Fantasma', 13, 2800, 'Bestia Mágica', 28);
INSERT INTO monstruos VALUES (23, 'Vampiro Ancestral', 16, 3900, 'No-Muerto', 23);
INSERT INTO monstruos VALUES (24, 'Demonio Menor', 9, 1600, 'Demonio', 24);
INSERT INTO monstruos VALUES (25, 'Harpía', 8, 1400, 'Bestia Alada', 25);
INSERT INTO monstruos VALUES (26, 'Bestia del Pantano', 10, 2100, 'Bestia', 30);
INSERT INTO monstruos VALUES (27, 'Kraken', 25, 6000, 'Bestia Marina', 27);
INSERT INTO monstruos VALUES (28, 'Espectro Errante', 12, 2600, 'No-Muerto', 19);
INSERT INTO monstruos VALUES (29, 'Gólem de Piedra', 14, 3000, 'Elemental', 29);
INSERT INTO monstruos VALUES (30, 'Reina Araña', 15, 3400, 'Bestia Mítica', 21);

-- MISIONES
INSERT INTO misiones VALUES (1, 'Defender la Fortaleza', 'Difícil', 1500, 200, 1, 1);
INSERT INTO misiones VALUES (2, 'Cazar al Dragón Rojo', 'Muy Difícil', 3000, 500, 2, 2);
INSERT INTO misiones VALUES (3, 'Rescate en la Montaña', 'Intermedio', 1200, 150, 3, 3);
INSERT INTO misiones VALUES (4, 'Elixir de los Antiguos', 'Fácil', 500, 50, 4, 4);
INSERT INTO misiones VALUES (5, 'Invasión Goblin', 'Difícil', 1800, 250, 5, 5);
INSERT INTO misiones VALUES (6, 'Asalto al Castillo Oscuro', 'Muy Difícil', 3200, 600, 6, 6);
INSERT INTO misiones VALUES (7, 'Explorar las Ruinas Perdidas', 'Intermedio', 1100, 120, 7, 7);
INSERT INTO misiones VALUES (8, 'Emboscada en el Bosque', 'Fácil', 600, 70, 8, 8);
INSERT INTO misiones VALUES (9, 'Capturar al Señor Bandido', 'Difícil', 1600, 220, 9, 9);
INSERT INTO misiones VALUES (10, 'El Secreto del Lago', 'Intermedio', 1300, 170, 10, 10);
INSERT INTO misiones VALUES (11, 'Cazar al Fénix', 'Muy Difícil', 3500, 650, 11, 11);
INSERT INTO misiones VALUES (12, 'Defensa del Pueblo', 'Fácil', 400, 40, 12, 12);
INSERT INTO misiones VALUES (13, 'Invasión de No-Muertos', 'Difícil', 1700, 230, 13, 13);
INSERT INTO misiones VALUES (14, 'Asedio a la Ciudadela', 'Muy Difícil', 2900, 520, 14, 14);
INSERT INTO misiones VALUES (15, 'Patrullar la Frontera', 'Intermedio', 1000, 110, 15, 15);
INSERT INTO misiones VALUES (16, 'Ritual en las Cavernas', 'Fácil', 700, 80, 16, 16);
INSERT INTO misiones VALUES (17, 'Batalla en el Valle de la Muerte', 'Muy Difícil', 3400, 620, 17, 17);
INSERT INTO misiones VALUES (18, 'Liberar el Templo', 'Difícil', 2000, 280, 18, 18);
INSERT INTO misiones VALUES (19, 'Recuperar el Artefacto Perdido', 'Intermedio', 900, 100, 19, 19);
INSERT INTO misiones VALUES (20, 'Expulsar al Hechicero Oscuro', 'Muy Difícil', 3200, 600, 20, 20);
INSERT INTO misiones VALUES (21, 'Defender el Bastión', 'Difícil', 1900, 260, 21, 21);
INSERT INTO misiones VALUES (22, 'Cazar a la Hidra', 'Muy Difícil', 3700, 680, 22, 22);
INSERT INTO misiones VALUES (23, 'Investigar las Ruinas Antiguas', 'Intermedio', 1400, 160, 23, 23);
INSERT INTO misiones VALUES (24, 'Destruir el Portal Oscuro', 'Difícil', 2100, 300, 24, 24);
INSERT INTO misiones VALUES (25, 'Capturar al Mago Rebelde', 'Intermedio', 800, 90, 25, 25);
INSERT INTO misiones VALUES (26, 'Cazar a los Ogros', 'Difícil', 1800, 240, 26, 26);
INSERT INTO misiones VALUES (27, 'Salvar a los Prisioneros', 'Fácil', 500, 50, 27, 27);
INSERT INTO misiones VALUES (28, 'Caza de Bestias Salvajes', 'Intermedio', 1100, 120, 28, 28);
INSERT INTO misiones VALUES (29, 'Derrotar al Señor de la Guerra', 'Muy Difícil', 3300, 630, 29, 29);
INSERT INTO misiones VALUES (30, 'Misterio en el Pantano', 'Intermedio', 1000, 110, 30, 30);

-- EQUIPAMIENTOS
INSERT INTO equipamientos VALUES (1, 'Espada Cortante', 'arma', 1, 5, 0);
INSERT INTO equipamientos VALUES (2, 'Escudo de Hierro', 'escudo', 1, 0, 3);
INSERT INTO equipamientos VALUES (3, 'Armadura de Cuero', 'armadura', 2, 0, 4);
INSERT INTO equipamientos VALUES (4, 'Hacha de Batalla', 'arma', 3, 7, 0);
INSERT INTO equipamientos VALUES (5, 'Capa de Protección', 'accesorio', 2, 0, 5);
INSERT INTO equipamientos VALUES (6, 'Báculo de Hechicería', 'arma', 5, 6, 0);
INSERT INTO equipamientos VALUES (7, 'Guantes de Batalla', 'accesorio', 4, 3, 2);
INSERT INTO equipamientos VALUES (8, 'Botas de Velocidad', 'accesorio', 3, 2, 1);
INSERT INTO equipamientos VALUES (9, 'Espada Larga', 'arma', 4, 8, 0);
INSERT INTO equipamientos VALUES (10, 'Escudo de Cristal', 'escudo', 5, 0, 6);
INSERT INTO equipamientos VALUES (11, 'Armadura de Placas', 'armadura', 6, 0, 10);
INSERT INTO equipamientos VALUES (12, 'Hacha de Dos Manos', 'arma', 7, 10, 0);
INSERT INTO equipamientos VALUES (13, 'Capa de Sigilo', 'accesorio', 5, 0, 7);
INSERT INTO equipamientos VALUES (14, 'Espada de Fuego', 'arma', 8, 9, 0);
INSERT INTO equipamientos VALUES (15, 'Anillo de Poder', 'accesorio', 6, 4, 0);
INSERT INTO equipamientos VALUES (16, 'Guantes de Agilidad', 'accesorio', 4, 2, 1);
INSERT INTO equipamientos VALUES (17, 'Báculo de Fuego', 'arma', 9, 12, 0);
INSERT INTO equipamientos VALUES (18, 'Botas de la Agilidad', 'accesorio', 3, 1, 2);
INSERT INTO equipamientos VALUES (19, 'Armadura de Acero', 'armadura', 5, 0, 8);
INSERT INTO equipamientos VALUES (20, 'Espada de Hielo', 'arma', 9, 11, 0);
INSERT INTO equipamientos VALUES (21, 'Escudo de la Fe', 'escudo', 7, 0, 5);
INSERT INTO equipamientos VALUES (22, 'Capa de la Noche', 'accesorio', 6, 0, 8);
INSERT INTO equipamientos VALUES (23, 'Espada de Luz', 'arma', 10, 13, 0);
INSERT INTO equipamientos VALUES (24, 'Hacha de Guerrero', 'arma', 8, 9, 0);
INSERT INTO equipamientos VALUES (25, 'Guantes de Hechicero', 'accesorio', 7, 2, 0);
INSERT INTO equipamientos VALUES (26, 'Báculo del Viento', 'arma', 10, 14, 0);
INSERT INTO equipamientos VALUES (27, 'Armadura del Dragón', 'armadura', 10, 0, 12);
INSERT INTO equipamientos VALUES (28, 'Anillo de Invulnerabilidad', 'accesorio', 9, 0, 10);
INSERT INTO equipamientos VALUES (29, 'Escudo del Valor', 'escudo', 8, 0, 7);
INSERT INTO equipamientos VALUES (30, 'Capa de Resistencia', 'accesorio', 7, 0, 6);

-- JUGADORES_MISIONES (Con TO_DATE y cambio de TRUE/FALSE a 1/0)
INSERT INTO jugadores_misiones VALUES (1, 1, TO_DATE('2024-01-15', 'YYYY-MM-DD'), 1);
INSERT INTO jugadores_misiones VALUES (1, 2, TO_DATE('2024-01-20', 'YYYY-MM-DD'), 1);
INSERT INTO jugadores_misiones VALUES (1, 3, NULL, 0);
INSERT INTO jugadores_misiones VALUES (2, 2, TO_DATE('2024-01-22', 'YYYY-MM-DD'), 1);
INSERT INTO jugadores_misiones VALUES (2, 4, NULL, 0);
INSERT INTO jugadores_misiones VALUES (3, 5, TO_DATE('2024-02-10', 'YYYY-MM-DD'), 1);
INSERT INTO jugadores_misiones VALUES (3, 6, TO_DATE('2024-02-15', 'YYYY-MM-DD'), 1);
INSERT INTO jugadores_misiones VALUES (4, 7, NULL, 0);
INSERT INTO jugadores_misiones VALUES (4, 8, TO_DATE('2024-03-10', 'YYYY-MM-DD'), 1);
INSERT INTO jugadores_misiones VALUES (5, 9, NULL, 0);
INSERT INTO jugadores_misiones VALUES (5, 10, TO_DATE('2024-03-18', 'YYYY-MM-DD'), 1);
INSERT INTO jugadores_misiones VALUES (6, 11, TO_DATE('2024-03-20', 'YYYY-MM-DD'), 1);
INSERT INTO jugadores_misiones VALUES (6, 12, NULL, 0);
INSERT INTO jugadores_misiones VALUES (7, 13, TO_DATE('2024-04-15', 'YYYY-MM-DD'), 1);
INSERT INTO jugadores_misiones VALUES (7, 14, NULL, 0);
INSERT INTO jugadores_misiones VALUES (8, 15, TO_DATE('2024-05-01', 'YYYY-MM-DD'), 1);
INSERT INTO jugadores_misiones VALUES (8, 16, TO_DATE('2024-05-05', 'YYYY-MM-DD'), 1);
INSERT INTO jugadores_misiones VALUES (9, 17, NULL, 0);
INSERT INTO jugadores_misiones VALUES (9, 18, TO_DATE('2024-05-15', 'YYYY-MM-DD'), 1);
INSERT INTO jugadores_misiones VALUES (10, 19, TO_DATE('2024-05-20', 'YYYY-MM-DD'), 1);
INSERT INTO jugadores_misiones VALUES (10, 20, NULL, 0);
INSERT INTO jugadores_misiones VALUES (1, 21, NULL, 0);
INSERT INTO jugadores_misiones VALUES (2, 22, TO_DATE('2024-06-10', 'YYYY-MM-DD'), 1);
INSERT INTO jugadores_misiones VALUES (3, 23, NULL, 0);
INSERT INTO jugadores_misiones VALUES (4, 24, TO_DATE('2024-07-01', 'YYYY-MM-DD'), 1);
INSERT INTO jugadores_misiones VALUES (5, 25, TO_DATE('2024-07-05', 'YYYY-MM-DD'), 1);
INSERT INTO jugadores_misiones VALUES (6, 26, NULL, 0);
INSERT INTO jugadores_misiones VALUES (7, 27, TO_DATE('2024-07-15', 'YYYY-MM-DD'), 1);
INSERT INTO jugadores_misiones VALUES (8, 28, NULL, 0);
INSERT INTO jugadores_misiones VALUES (9, 29, TO_DATE('2024-08-05', 'YYYY-MM-DD'), 1);
INSERT INTO jugadores_misiones VALUES (10, 30, NULL, 0);
INSERT INTO jugadores_misiones VALUES (1, 24, TO_DATE('2024-08-15', 'YYYY-MM-DD'), 1);

-- JUGADORES_EQUIPAMIENTOS
INSERT INTO jugadores_equipamientos VALUES (1, 1, 1);
INSERT INTO jugadores_equipamientos VALUES (1, 2, 1);
INSERT INTO jugadores_equipamientos VALUES (1, 3, 1);
INSERT INTO jugadores_equipamientos VALUES (2, 4, 2);
INSERT INTO jugadores_equipamientos VALUES (2, 5, 1);
INSERT INTO jugadores_equipamientos VALUES (3, 6, 1);
INSERT INTO jugadores_equipamientos VALUES (3, 7, 2);
INSERT INTO jugadores_equipamientos VALUES (4, 8, 1);
INSERT INTO jugadores_equipamientos VALUES (4, 9, 1);
INSERT INTO jugadores_equipamientos VALUES (5, 10, 3);
INSERT INTO jugadores_equipamientos VALUES (5, 11, 1);
INSERT INTO jugadores_equipamientos VALUES (6, 12, 2);
INSERT INTO jugadores_equipamientos VALUES (6, 13, 1);
INSERT INTO jugadores_equipamientos VALUES (7, 14, 1);
INSERT INTO jugadores_equipamientos VALUES (7, 15, 1);
INSERT INTO jugadores_equipamientos VALUES (8, 16, 1);
INSERT INTO jugadores_equipamientos VALUES (8, 17, 2);
INSERT INTO jugadores_equipamientos VALUES (9, 18, 1);
INSERT INTO jugadores_equipamientos VALUES (9, 19, 1);
INSERT INTO jugadores_equipamientos VALUES (10, 20, 2);
INSERT INTO jugadores_equipamientos VALUES (10, 21, 1);
INSERT INTO jugadores_equipamientos VALUES (1, 22, 1);
INSERT INTO jugadores_equipamientos VALUES (2, 23, 3);
INSERT INTO jugadores_equipamientos VALUES (3, 24, 1);
INSERT INTO jugadores_equipamientos VALUES (4, 25, 1);
INSERT INTO jugadores_equipamientos VALUES (5, 26, 1);
INSERT INTO jugadores_equipamientos VALUES (6, 27, 2);
INSERT INTO jugadores_equipamientos VALUES (7, 28, 1);
INSERT INTO jugadores_equipamientos VALUES (8, 29, 1);
INSERT INTO jugadores_equipamientos VALUES (9, 30, 1);
INSERT INTO jugadores_equipamientos VALUES (10, 1, 1);

-- JUGADORES_RECOMPENSAS
INSERT INTO jugadores_recompensas VALUES (1, 1, TO_DATE('2024-01-15', 'YYYY-MM-DD'));
INSERT INTO jugadores_recompensas VALUES (1, 2, TO_DATE('2024-01-20', 'YYYY-MM-DD'));
INSERT INTO jugadores_recompensas VALUES (2, 3, TO_DATE('2024-01-22', 'YYYY-MM-DD'));
INSERT INTO jugadores_recompensas VALUES (2, 4, TO_DATE('2024-02-01', 'YYYY-MM-DD'));
INSERT INTO jugadores_recompensas VALUES (3, 5, TO_DATE('2024-02-10', 'YYYY-MM-DD'));
INSERT INTO jugadores_recompensas VALUES (3, 6, TO_DATE('2024-02-15', 'YYYY-MM-DD'));
INSERT INTO jugadores_recompensas VALUES (4, 7, TO_DATE('2024-03-05', 'YYYY-MM-DD'));
INSERT INTO jugadores_recompensas VALUES (4, 8, TO_DATE('2024-03-10', 'YYYY-MM-DD'));
INSERT INTO jugadores_recompensas VALUES (5, 9, TO_DATE('2024-03-12', 'YYYY-MM-DD'));
INSERT INTO jugadores_recompensas VALUES (5, 10, TO_DATE('2024-03-18', 'YYYY-MM-DD'));
INSERT INTO jugadores_recompensas VALUES (6, 11, TO_DATE('2024-03-20', 'YYYY-MM-DD'));
INSERT INTO jugadores_recompensas VALUES (6, 12, TO_DATE('2024-04-01', 'YYYY-MM-DD'));
INSERT INTO jugadores_recompensas VALUES (7, 13, TO_DATE('2024-04-15', 'YYYY-MM-DD'));
INSERT INTO jugadores_recompensas VALUES (7, 14, TO_DATE('2024-04-20', 'YYYY-MM-DD'));
INSERT INTO jugadores_recompensas VALUES (8, 15, TO_DATE('2024-05-01', 'YYYY-MM-DD'));
INSERT INTO jugadores_recompensas VALUES (8, 16, TO_DATE('2024-05-05', 'YYYY-MM-DD'));
INSERT INTO jugadores_recompensas VALUES (9, 17, TO_DATE('2024-05-10', 'YYYY-MM-DD'));
INSERT INTO jugadores_recompensas VALUES (9, 18, TO_DATE('2024-05-15', 'YYYY-MM-DD'));
INSERT INTO jugadores_recompensas VALUES (10, 19, TO_DATE('2024-05-20', 'YYYY-MM-DD'));
INSERT INTO jugadores_recompensas VALUES (10, 20, TO_DATE('2024-06-01', 'YYYY-MM-DD'));
INSERT INTO jugadores_recompensas VALUES (1, 21, TO_DATE('2024-06-05', 'YYYY-MM-DD'));
INSERT INTO jugadores_recompensas VALUES (2, 22, TO_DATE('2024-06-10', 'YYYY-MM-DD'));
INSERT INTO jugadores_recompensas VALUES (3, 23, TO_DATE('2024-06-15', 'YYYY-MM-DD'));
INSERT INTO jugadores_recompensas VALUES (4, 24, TO_DATE('2024-07-01', 'YYYY-MM-DD'));
INSERT INTO jugadores_recompensas VALUES (5, 25, TO_DATE('2024-07-05', 'YYYY-MM-DD'));
INSERT INTO jugadores_recompensas VALUES (6, 26, TO_DATE('2024-07-10', 'YYYY-MM-DD'));
INSERT INTO jugadores_recompensas VALUES (7, 27, TO_DATE('2024-07-15', 'YYYY-MM-DD'));
INSERT INTO jugadores_recompensas VALUES (8, 28, TO_DATE('2024-08-01', 'YYYY-MM-DD'));
INSERT INTO jugadores_recompensas VALUES (9, 29, TO_DATE('2024-08-05', 'YYYY-MM-DD'));
INSERT INTO jugadores_recompensas VALUES (10, 30, TO_DATE('2024-08-10', 'YYYY-MM-DD'));
INSERT INTO jugadores_recompensas VALUES (1, 4, TO_DATE('2024-08-15', 'YYYY-MM-DD'));

-- Hacemos permanente la inserción de datos en la sesión de Oracle
COMMIT;